### PR TITLE
fix: VP9 HWAccel

### PR DESCRIPTION
**Pull request by alexmercerind**
Adds a VP9 Video Toolbox decoder to `ffmpeg` to fix freezes on macOS Intel based hardware.

Refs:
- https://trac.ffmpeg.org/ticket/9599
- https://trac.ffmpeg.org/attachment/ticket/9599/ticket-9599.patch

Thanks:
- @23doors for bringing this into sight
- @low-batt for its patch uploaded to FFmpeg tracker

### CODE REVIEW

**Comment by low-batt** [comment]
Be aware these changes were prepared by someone who is not a FFmpeg developer and has not dug into the FFmpeg sources before. I have tested this patch and confirmed VP9 decoding is working on my Intel Mac with these changes. This patch has not been submitted to FFmpeg yet.

My plan is to look into the FFmpeg sources some more to see if other changes are required when adding a decoder. I'm juggling multiple tasks at the moment. My true plan is to delay a bit and hope an actual FFmpeg developer notices this problem and takes over before I get back to it.

Just making sure you know these changes have not been reviewed by an actual FFmpeg developer…

**Comment by alexmercerind** [comment]
We trust you.

**Comment by low-batt** [comment]
Thanks. I am sure that the root cause has been properly identified and changing the BSF filter is the correct fix. Where I'm a bit uncertain is exactly how the generic decoder portion of FFmpeg selects a particular decoder when decoding without hardware acceleration. And I lack the hardware needed to confirm this new decoder is not selected under Linux or Windows.

I will try and find some time to look into that some more. If a FFmpeg developer shows up and proposes changes or a different patch I will make certain the media-kit project knows about it.

**Review by birros — APPROVED** [review]
I approve, but we still need to check that no regression is introduced, especially for iOS.

**Pull request merged**
